plugins:
  - aws-amplify-serverless-plugin

custom:
  # Our stage is based on what is passed in when running serverless commands,
  # or falls back to what we have set in the provider section
  stage: ${opt:stage, self:provider.stage}
  resourcesStages:
    prod: prod
    dev: dev
  resourcesStage: ${self:custom.resourcesStages.${self:custom.stage}, self:custom.resourcesStages.dev}
  amplify:
    - filename: ../notes-client/arc/aws-exports.js
      type: javascript
      appClient: WebUserPoolClient

lambdaPolicyXRay:
  Effect: Allow
  Action:
    - xray:PutTraceSegments
    - xray:PutTelemetryRecords
  Resource: '*'

resources:
  Resources:
    # An app client for the Amazon Cognito user pool
    WebUserPoolClient:
      Type: 'AWS::Cognito::UserPoolClient'
      Description: 'App Client for Web Usage'
      Properties:
        ClientName: ${self:provider.apiname}-web-cognitoclient
        GenerateSecret: false
        UserPoolId: {Ref: UserPool}
